version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Admin-123
      MYSQL_DATABASE: order_db
    ports:
      - "3306:3306"
  order-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Admin-123
      DB_NAME: order_db
    depends_on:
      - db
